--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BedrockBlock/BlockRender
build-by-default: true
branches:
- master
projects:
  BlockRender:
    lint:
      nonPsr: false
      syntaxError: false
    path: ""
...
